"""Core FastCPI product copy in the twelve inherited UI languages."""

from __future__ import annotations

COPY = {
    "eyebrow": {"en":"B2B web-market intelligence","et":"B2B veebituru hinnateave","de":"B2B-Webmarkt-Intelligence","fr":"Intelligence des marchés web B2B","sv":"B2B-marknadsinformation från webben","lv":"B2B tīmekļa tirgus izpēte","no":"B2B-markedsinnsikt fra nettet","da":"B2B-markedsindsigt fra nettet","pl":"Analiza internetowego rynku B2B","nl":"B2B-webmarktinzichten","fi":"B2B-verkkomarkkinatieto","lt":"B2B interneto rinkos įžvalgos"},
    "headline": {"en":"Know what the market is asking.","et":"Tea, millist hinda turg küsib.","de":"Wissen, was der Markt verlangt.","fr":"Connaissez les prix demandés par le marché.","sv":"Se vilka priser marknaden begär.","lv":"Uzziniet tirgus piedāvātās cenas.","no":"Se hvilke priser markedet ber om.","da":"Se hvilke priser markedet tager.","pl":"Poznaj ceny ofertowe rynku.","nl":"Weet welke prijzen de markt vraagt.","fi":"Tiedä, mitä hintoja markkinoilla pyydetään.","lt":"Žinokite, kokių kainų prašo rinka."},
    "hero": {"en":"FastCPI observes public supplier prices for goods and services, normalises comparable terms, and preserves the source evidence.","et":"FastCPI jälgib kaupade ja teenuste avalikke tarnijahindu, ühtlustab võrreldavad tingimused ning säilitab allikatõendid.","de":"FastCPI beobachtet öffentliche Lieferantenpreise für Waren und Dienstleistungen, normalisiert vergleichbare Konditionen und bewahrt die Quellenbelege.","fr":"FastCPI observe les prix publics des fournisseurs, normalise les conditions comparables et conserve les preuves de source.","sv":"FastCPI observerar offentliga leverantörspriser, normaliserar jämförbara villkor och bevarar källbevis.","lv":"FastCPI novēro publiskas piegādātāju cenas, normalizē salīdzināmus nosacījumus un saglabā avotu pierādījumus.","no":"FastCPI observerer offentlige leverandørpriser, normaliserer sammenlignbare vilkår og bevarer kildedokumentasjon.","da":"FastCPI observerer offentlige leverandørpriser, normaliserer sammenlignelige vilkår og bevarer kildedokumentation.","pl":"FastCPI obserwuje publiczne ceny dostawców, normalizuje porównywalne warunki i zachowuje dowody źródłowe.","nl":"FastCPI observeert openbare leveranciersprijzen, normaliseert vergelijkbare voorwaarden en bewaart bronbewijs.","fi":"FastCPI seuraa julkisia toimittajahintoja, normalisoi vertailukelpoiset ehdot ja säilyttää lähdetodisteet.","lt":"FastCPI stebi viešas tiekėjų kainas, normalizuoja palyginamas sąlygas ir išsaugo šaltinių įrodymus."},
    "query_modes": {"en":"Search in plain language, by SKU or GTIN, or across a CPV division and all of its descendants.","et":"Otsi tavakeeles, SKU või GTIN-i järgi või CPV jaotise ning kõigi alamkoodide lõikes.","de":"Suchen Sie in Alltagssprache, nach SKU oder GTIN oder in einer CPV-Abteilung mit allen Unterkategorien.","fr":"Recherchez en langage naturel, par SKU ou GTIN, ou dans une division CPV et tous ses descendants.","sv":"Sök med vanligt språk, SKU eller GTIN, eller i en CPV-division och alla underkoder.","lv":"Meklējiet brīvā valodā, pēc SKU vai GTIN, vai CPV sadaļā un visos tās apakškodos.","no":"Søk med vanlig språk, SKU eller GTIN, eller i en CPV-divisjon og alle underkoder.","da":"Søg med almindeligt sprog, SKU eller GTIN eller i en CPV-division og alle underkoder.","pl":"Szukaj językiem naturalnym, według SKU lub GTIN albo w dziale CPV i jego podkategoriach.","nl":"Zoek in gewone taal, op SKU of GTIN, of in een CPV-divisie en alle onderliggende codes.","fi":"Hae luonnollisella kielellä, SKU- tai GTIN-tunnuksella tai CPV-jaosta kaikkine alakoodeineen.","lt":"Ieškokite natūralia kalba, pagal SKU ar GTIN arba CPV skyriuje ir visuose jo poklasiuose."},
    "google": {"en":"Sign in with Google","et":"Logi Google'iga sisse","de":"Mit Google anmelden","fr":"Se connecter avec Google","sv":"Logga in med Google","lv":"Pierakstīties ar Google","no":"Logg inn med Google","da":"Log ind med Google","pl":"Zaloguj się przez Google","nl":"Inloggen met Google","fi":"Kirjaudu Googlella","lt":"Prisijungti su Google"},
    "invite": {"en":"Invite-only during the initial release.","et":"Esialgu ainult kutsega.","de":"In der ersten Version nur auf Einladung.","fr":"Accès sur invitation pendant le lancement initial.","sv":"Endast med inbjudan under den första lanseringen.","lv":"Sākotnējā laidienā piekļuve tikai ar ielūgumu.","no":"Kun med invitasjon i den første lanseringen.","da":"Kun med invitation i den første lancering.","pl":"W pierwszej wersji dostęp tylko na zaproszenie.","nl":"Tijdens de eerste release alleen op uitnodiging.","fi":"Alkuvaiheessa käyttö vain kutsulla.","lt":"Pradiniame etape prieiga tik su kvietimu."},
    "chat_title": {"en":"What should we benchmark?","et":"Mida peaksime võrdlema?","de":"Was sollen wir benchmarken?","fr":"Que devons-nous comparer ?","sv":"Vad ska vi jämföra?","lv":"Ko vēlaties salīdzināt?","no":"Hva skal vi sammenligne?","da":"Hvad skal vi benchmarke?","pl":"Co mamy porównać?","nl":"Wat zullen we benchmarken?","fi":"Mitä vertaillaan?","lt":"Ką turėtume palyginti?"},
    "chat_body": {"en":"Search public B2B prices by description, CPV code, SKU, MPN or GTIN.","et":"Otsi avalikke B2B-hindu kirjelduse, CPV-koodi, SKU, MPN-i või GTIN-i järgi.","de":"Suchen Sie öffentliche B2B-Preise nach Beschreibung, CPV-Code, SKU, MPN oder GTIN.","fr":"Recherchez des prix B2B publics par description, code CPV, SKU, MPN ou GTIN.","sv":"Sök offentliga B2B-priser med beskrivning, CPV-kod, SKU, MPN eller GTIN.","lv":"Meklējiet publiskas B2B cenas pēc apraksta, CPV koda, SKU, MPN vai GTIN.","no":"Søk offentlige B2B-priser etter beskrivelse, CPV-kode, SKU, MPN eller GTIN.","da":"Søg offentlige B2B-priser efter beskrivelse, CPV-kode, SKU, MPN eller GTIN.","pl":"Szukaj publicznych cen B2B według opisu, kodu CPV, SKU, MPN lub GTIN.","nl":"Zoek openbare B2B-prijzen op beschrijving, CPV-code, SKU, MPN of GTIN.","fi":"Hae julkisia B2B-hintoja kuvauksella, CPV-koodilla, SKU:lla, MPN:llä tai GTIN:llä.","lt":"Ieškokite viešų B2B kainų pagal aprašymą, CPV kodą, SKU, MPN ar GTIN."},
    "placeholder": {"en":"Ask for a good, service, CPV code or SKU...","et":"Küsi kauba, teenuse, CPV-koodi või SKU kohta...","de":"Nach Ware, Dienstleistung, CPV-Code oder SKU fragen...","fr":"Demandez un bien, service, code CPV ou SKU…","sv":"Fråga efter en vara, tjänst, CPV-kod eller SKU...","lv":"Jautājiet par preci, pakalpojumu, CPV kodu vai SKU...","no":"Spør etter en vare, tjeneste, CPV-kode eller SKU...","da":"Spørg efter en vare, tjeneste, CPV-kode eller SKU...","pl":"Zapytaj o towar, usługę, kod CPV lub SKU...","nl":"Vraag naar een product, dienst, CPV-code of SKU...","fi":"Kysy tuotteesta, palvelusta, CPV-koodista tai SKU:sta...","lt":"Klauskite apie prekę, paslaugą, CPV kodą ar SKU..."}
}


def tr(key: str, lang: str = "en") -> str:
    values = COPY.get(key, {})
    return values.get(lang, values.get("en", key))
